# Generated by Django 4.2.2 on 2023-06-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
