# Generated by Django 4.2.2 on 2023-07-05 16:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pss', '0005_alter_attendancemodel_date_btechmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 21, 59, 26, 651198)),
        ),
        migrations.CreateModel(
            name='DiplomaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('marks', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
