# Generated by Django 4.2.2 on 2023-07-05 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pss', '0006_alter_attendancemodel_date_diplomamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 22, 12, 21, 424380)),
        ),
        migrations.CreateModel(
            name='FeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 5, 22, 12, 21, 425382))),
                ('particulars', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
