# Generated by Django 4.2.2 on 2023-07-07 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0007_alter_attendancemodel_date_feemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemodel',
            name='recipt',
            field=models.ImageField(default=None, upload_to='recipts/<django.db.models.fields.related.ForeignKey>/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 19, 17, 7, 587723)),
        ),
        migrations.AlterField(
            model_name='feemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 19, 17, 7, 588721)),
        ),
    ]
