# Generated by Django 4.2.2 on 2023-07-07 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0008_feemodel_recipt_alter_attendancemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 19, 22, 35, 252508)),
        ),
        migrations.AlterField(
            model_name='feemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 19, 22, 35, 253507)),
        ),
        migrations.AlterField(
            model_name='feemodel',
            name='recipt',
            field=models.ImageField(upload_to='recipts/'),
        ),
    ]
