# Generated by Django 4.2.2 on 2023-07-14 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0010_alter_attendancemodel_date_alter_feemodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('stock_added_date', models.DateTimeField(default=datetime.datetime(2023, 7, 14, 9, 16, 25, 992100))),
            ],
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 9, 16, 25, 991082)),
        ),
        migrations.AlterField(
            model_name='feemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 9, 16, 25, 991082)),
        ),
    ]
