# Generated by Django 4.2.2 on 2023-07-27 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0011_groceriesmodel_alter_attendancemodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 11, 47, 53, 803963)),
        ),
        migrations.AlterField(
            model_name='feemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 11, 47, 53, 804967)),
        ),
        migrations.AlterField(
            model_name='groceriesmodel',
            name='stock_added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 11, 47, 53, 805972)),
        ),
    ]
